### ISSUE TITLE
ultravox 0.4.1 doesn't work with vllm

### ISSUE THREAD

**Issue by Madoshakalaka** [fixie-ai/ultravox#272]
with the dependency:
```toml
[tool.poetry.dependencies]
vllm = {extras = ["audio"], version = "^0.6.6.post1"}
transformers = "^4.47.0" # same as ultravox main branch
```

following this example here:
(but with "fixie-ai/ultravox-v0_3" changed to "fixie-ai/ultravox-v0_4_1-llama-3_1-8b")

https://github.com/vllm-project/vllm/blob/0794e7446efca1fd7b8ea1cde96777897660cdea/examples/offline_inference/audio_language.py#L27-L45

the error I got:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ME/Projects/my-project/./main.py", line 28, in <module>
[rank0]:     llm = LLM(model="fixie-ai/ultravox-v0_4_1-llama-3_1-8b", task="generate", trust_remote_code=True)
...
[rank0]:   File "/home/ME/.cache/pypoetry/virtualenvs/my-project-7y5QMYrF-py3.10/lib/python3.10/site-packages/vllm/inputs/registry.py", line 108, in get_hf_processor
[rank0]:     raise TypeError("Invalid type of HuggingFace processor. "
[rank0]: TypeError: Invalid type of HuggingFace processor. Expected type: <class 'transformers.processing_utils.ProcessorMixin'>, but found type: <class 'transformers.tokenization_utils_fast.PreTrainedTokenizerFast'>
```
